appSuffix: abc
appSourceBasePath: overlays/dev/dev01/cluster-config

default:
  application:
    enabled: false
    namespace: "openshift-gitops"
    destination:
      server: https://kubernetes.default.svc
      namespace: "openshift-gitops"
    project: "default"
    source:
      repoURL: https://github.com/my-org/my-repo
      targetRevision: main

  project:
    enabled: true
    annotations:
      argocd.argoproj.io/sync-wave: "-2"
    extraFields:
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'

projects:
  example:
    description: Project for cluster cp1-hub

applications:
  disco-operators:
    enabled: true
    annotations:
      argocd.argoproj.io/sync-wave: "0"
    source:
      path: disco-operators
