apiVersion: v2
name: tenant-namespaces
description: A multi-tenant onboarding chart that automates namespace creation, resource governance, and Argo CD project delegation for development teams

type: application

version: 1.0.1

appVersion: "1.0.0"
