{{- if and $.Values.project $.Values.project.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.project.name | quote }}
  namespace: {{ $.Values.argocdNamespace | quote }}
spec:
  description: {{ .Values.project.description | quote }}
  sourceRepos:
    {{- toYaml .Values.project.sourceRepos | nindent 4 }}
  destinations:
    {{- toYaml .Values.project.destinations | nindent 4 }}
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    {{- toYaml .Values.project.roles | nindent 4 }}
{{- end }}
