{{- range $namespace := .Values.namespaces }}
{{- $nsConfig := mergeOverwrite (deepCopy $.Values.defaults.namespace) ($namespace.namespace | default dict) }}
{{- if $nsConfig.features.enableCertificateConfigMap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: user-ca-bundle
    namespace: {{ $namespace.name | quote }}
    labels:
      config.openshift.io/inject-trusted-cabundle: 'true'
{{- end }}
{{- end }}
