{{- range $namespace := .Values.namespaces }}
{{- if ($namespace.namespace.features.enableCertificateConfigMap | default $.Values.defaults.namespace.features.enableCertificateConfigMap | default false) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: user-ca-bundle
    namespace: {{ $namespace.name | quote }}
    labels:
      config.openshift.io/inject-trusted-cabundle: 'true'
{{- end }}
{{- end }}
