{{- range $namespace := .Values.namespaces }}
{{- $limitRange := mergeOverwrite (deepCopy $.Values.defaults.limitRange) ($namespace.limitRange | default dict) }}
{{- if $limitRange.enabled | default false }}
---
kind: LimitRange
apiVersion: v1
metadata:
  name: {{ $limitRange.name | default "default" | quote }}
  namespace: {{ $namespace.name | quote }}
spec:
  limits:
    {{- with $limitRange.container }}
    {{- if .enabled | default false }}
    - type: Container
      {{- .values | toYaml | nindent 6 }}
    {{- end }}
    {{- end }}

    {{- with $limitRange.pod }}
    {{- if .enabled | default false }}
    - type: Pod
      {{- .values | toYaml | nindent 6 }}
    {{- end }}
    {{- end }}

    {{- with $limitRange.pvc }}
    {{- if .enabled | default false }}
    - type: PersistentVolumeClaim
      {{- .values | toYaml | nindent 6 }}
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}
