{{- range $namespace := .Values.namespaces }}
{{- $rbac := mergeOverwrite (deepCopy $.Values.defaults.rbac) ($namespace.rbac | default dict) }}
{{- if $rbac.enabled | default false }}
{{- range $roleBinding := $rbac.roleBindings }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $roleBinding.name | quote }}
  namespace: {{ $namespace.name | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $roleBinding.clusterRole }}
subjects:
  {{- range $group := $roleBinding.groups }}
  - kind: Group
    name: {{ $group | quote }}
    apiGroup: rbac.authorization.k8s.io
  {{- end }}
{{- end }}
{{ /* end for $rbac.enabled */ }}
{{- end }}
{{ /* end for range $namespace */ }}
{{- end }}
