name: "✨ Feature Request"
description: "Suggest a new feature or improvement for a Helm Chart."
title: "[FEATURE] "
labels: ["feature request"]
assignees: []
projects: ["redhat-consulting-services/1"]

body:
  - type: input
    id: chart_name
    attributes:
      label: "Chart Name"
      description: "Which Helm Chart is this feature request for?"
      placeholder: "e.g., cluster-user-defined-networks"

  - type: input
    id: feature
    attributes:
      label: "Feature Description"
      description: "Describe the feature you would like to see."
      placeholder: "e.g., Add support for a new network topology."

  - type: textarea
    id: benefits
    attributes:
      label: "Benefits / Use Cases"
      description: "Explain why this feature would be useful."

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Any alternatives you've considered, if any."
