apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: {{ include "cudn-definition.name" . }}
  labels:
    {{ .Values.labels | toYaml | nindent 4 }}
spec:
  namespaceSelector:
    matchLabels:
      {{ .Values.labels | toYaml | nindent 4 }}
  network:
    topology: Localnet
    {{- if eq .Values.type "Localnet" }}
    {{- with .Values.localnet }}
    localnet:
      {{ . | toYaml | nindent 6 }}
    {{- end }}
    {{- end }}

    {{- if eq .Values.type "Layer2" }}
    {{- with .Values.layer2 }}
    layer2:
      {{ . | toYaml | nindent 6 }}
    {{- end }}
    {{- end }}

    {{- if eq .Values.type "Layer3" }}
    {{- with .Values.layer3 }}
    layer3:
      {{ . | toYaml | nindent 6 }}
    {{- end }}
    {{- end }}
