{{- range $key,$val := .Values.projects }}
{{- $mergedValue := (mergeOverwrite (deepCopy $.Values.default.project) (deepCopy $val)) }}
{{- if $mergedValue.enabled | default false }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $key }}
  namespace: {{ $mergedValue.namespace | quote }}
  {{- with $mergedValue.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with $mergedValue.labels }}
  labels:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with $mergedValue.finalizers }}
  finalizers:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  {{- with $mergedValue.description }}
  description: {{ . | quote }}
  {{- end }}
  {{- with $mergedValue.sourceRepos }}
  sourceRepos:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $mergedValue.destinations }}
  destinations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $mergedValue.clusterResourceWhitelist }}
  clusterResourceWhitelist:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with $mergedValue.clusterResourceBlacklist }}
  clusterResourceBlacklist:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $mergedValue.namespaceResourceWhitelist }}
  namespaceResourceWhitelist:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $mergedValue.namespaceResourceBlacklist }}
  namespaceResourceBlacklist:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $mergedValue.roles }}
  roles:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $mergedValue.extraFields }}
  {{- . | toYaml | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
