apiVersion: batch/v1
kind: CronJob
metadata:
  name: ldap-group-syncer
  namespace: {{ .Values.namespace }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.cronjob.backoffLimit }}
      template:
        spec:
          serviceAccountName: ldap-group-syncer
          restartPolicy: Never
          containers:
          - name: ldap-group-sync
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            command:
            - /bin/bash
            - -c
            - oc adm groups sync --whitelist=/etc/config/whitelist.txt --sync-config=/etc/config/sync.yaml --confirm
            volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: ldap-ca
              mountPath: /etc/ldap-ca
            - name: ldap-secret
              mountPath: /etc/secrets
          volumes:
          - name: config-volume
            configMap:
              name: ldap-sync-config
          - name: ldap-ca
            configMap:
              name: ldap-sync-ca
          - name: ldap-secret
            secret:
              secretName: {{ .Values.ldap.secretName }}
