{{- if eq .Values.secretStrategy "externalSecret" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.ldap.secretName }}
  namespace: {{ .Values.namespace }}
spec:
  # Logic for fetching from external provider, e.g. vault
  data:
  - secretKey: bindPassword
    remoteRef:
      key: path/to/ldap/creds
{{- else if eq .Values.secretStrategy "sealedSecret" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.ldap.secretName }}
  namespace: {{ .Values.namespace }}
spec:
  # Encrypted data goes here
{{- end }}